name: Tower Docs build
# read more here
# https://help.github.com/en/articles/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
      - master

jobs:
  
  # markdown-link-check:
  #   name: Check markdown files links
  #   if: "!contains(github.event.head_commit.message, '[ci skip]')"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Markdown links check
  #       uses: ruzickap/action-my-markdown-link-checker@v1
  #       with:
  #         exclude: |
  #           README.md

  build:
    name: Tower docs build
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false

    steps:
      - name: Environment
        run: env | sort

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build docs
        run: make build

      - name: Publish website
        if: github.ref == 'refs/heads/master'
        run: |
          make publish
          make invalidate
        env:
          AWS_EC2_METADATA_DISABLED: true
          AWS_ACCESS_KEY_ID: ${{secrets.TOWER_DOCS_ACCESS}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.TOWER_DOCS_SECRET}}

